# Master database configuration - automatically populates storage_master table on startup
storage_configurations:
  - id: 1
    storage_name: grepx_master_sqlite
    storage_type: sqlite
    description: "Main SQLite master database for storing configuration and task metadata"
    connection_string: "sqlite:///data/grepx-master_1.db"
    file_path: "data/grepx-master_1.db"
    is_default: true
    active_flag: true
    max_connections: 10
    timeout_seconds: 30

  - id: 2
    storage_name: stock_analysis_mongodb
    storage_type: mongodb
    description: "MongoDB database for storing stock analysis data and task outputs"
    connection_string: "mongodb://admin:password123@localhost:27017/stock_analysis?authSource=admin"
    host: localhost
    port: 27017
    database_name: stock_analysis
    username: admin
    password: password123
    auth_source: admin
    is_default: false
    active_flag: true
    max_connections: 20
    timeout_seconds: 30